map_update_interval: 2.0
maxUrange: 2.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 10
minimumScore: 3
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.1
angularUpdate: 0.1
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 100
xmin: -0.1
ymin: -0.1
xmax: 0.1
ymax: 0.1
delta: 0.02
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005